services:
  # ================================================
  # Relational Database (Identity and Sessions)
  # ================================================
  db_users:
    image: postgres:15-alpine
    container_name: bank_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:z
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-network

  # ================================================
  # Financial Ledger (TigerBeetle)
  # ================================================
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle
    container_name: bank_ledger
    restart: always
    privileged: true 
    entrypoint: ["/bin/sh", "/scripts/init_tigerbeetle.sh"]
    ports:
      - "3000:3000"
    volumes:
      - tb_data:/data
      - ./database/init_tigerbeetle.sh:/scripts/init_tigerbeetle.sh:z
    networks:
      - banking-network

  # ================================================
  # Go Backend API
  # ================================================
  api:
    build: ./api
    container_name: bank_api
    platform: linux/amd64
    restart: always
    privileged: true  
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_users:5432/${POSTGRES_DB}?sslmode=disable
      - TB_ADDRESS=${TIGERBEETLE_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION_HOURS}
      - GIN_MODE=${GIN_MODE}
      - PORT=${SERVER_PORT}
    depends_on:
      - db_users
      - tigerbeetle
    networks:
      - banking-network
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536

  # ================================================
  # VITE Frontend with Vite + Svelte
  # ================================================
  web:
    build: ./web
    container_name: bank_web
    ports:
      - "5173:5173"
    volumes:
      # Synchronize your local code with the container for Hot Reload
      - ./web:/app:z
      # Prevents your local node_modules folder from overwriting the one in the container
      - /app/node_modules
    environment:
      # Forces Vite to detect file changes on Linux/Fedora systems
      - CHOKIDAR_USEPOLLING=true
      # We tell the frontend where our API lives
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - api

volumes:
  postgres_data:
  tb_data:

networks:
  banking-network:
    external: true